### ISSUE TITLE
[FR] Image-to-Image URL

### ISSUE THREAD

**Issue by Succubyss** [LagPixelLOL/cog-sdxl#8]
While you can supply a URL for some fields, doing so with Image-to-Image is not currently done.

Filename conflicts for caching are expected, so the best way to do it would probably be to base the filename off an xxHash of it. Then, you could store the URL as a key that points to that file so that if the URL is sent again, it doesn't have to be redownloaded.

**Comment by LagPixelLOL** [comment]
> While you can supply a URL for some fields, doing so with Image-to-Image is not currently done.

Really? I thought Cog can supply URL to the image field.

**Comment by LagPixelLOL** [comment]
`Files should be passed as HTTP URLs or data URLs.` quoted from input API document page.
So files can indeed be passed as URLs, I'll consider this case closed.

**Comment by Succubyss** [comment]
> `Files should be passed as HTTP URLs or data URLs.` quoted from input API document page. So files can indeed be passed as URLs, I'll consider this case closed.

I see. The reason I thought it wasn't implemented was because this line makes no mention that it accepts URLs, and furthermore it's typed as "Path":
`image: Path = Input(description="The image for image to image or as the base for inpainting (Will be scaled then cropped to the set width and height)", default=None),`

**Comment by Succubyss** [comment]
Yeah, it doesn't seem the Path type can accept URLs as paths, so I think this might need to be adjusted.
